export const uz = {
  app: {
    title: "Private Plans",
    description: "Shaxsiy o‘sish tizimi",
  },
  nav: {
    today: "Kerak",
    progress: "Tahlil",
    settings: "Sozlamalar",
  },
  common: {
    back: "Ortga",
    close: "Yopish",
    create: "Yaratish",
    continue: "Davom etish",
    save: "Saqlash",
    loading: "Yuklanmoqda",
    noData: "Hali ma’lumot yo‘q",
    noInsights: "Hali tahlil yo‘q",
    pending: "Kutilayotgan",
    completed: "Bajarildi",
    missed: "Bajarilmadi",
    later: "Keyinroq",
    none: "Yo‘q",
  },
  statusLabels: {
    planned: "Kutilayotgan",
    completed: "Bajarildi",
    missed: "Bajarilmadi",
  },
  health: {
    Healthy: "Sog‘lom",
    "At Risk": "E’tibor kerak",
    Inactive: "Faol emas",
  },
  today: {
    title: "Kerak",
    activeSystems: "faol tizim",
    done: "bajarildi",
    morningReset: "Tonggi reset",
    tomorrowPlanning: "Ertangi asosiy rejalar",
    eveningReset: "Kechki reset",
    morningSubtitle: "Bugungi niyat, energiya va asosiy fokusni belgilang.",
    tomorrowSubtitle: "Ertangi fokus, ustuvorlik va tizimlarni belgilang.",
    eveningSubtitle: "Bugungi kunni yakunlang, bajarilmagan tizimlar va refleksiyani ko‘ring.",
    focusMode: "Fokus rejimi",
    focusSubtitle: "25 daqiqalik sokin ijro",
    completedToday: "Bugun bajarildi",
    missedToday: "Bugun bajarilmadi",
    plannedToday: "Kutilmoqda",
  },
  create: {
    newGoal: "Yangi maqsad",
    newHabit: "Yangi odat",
    newSystem: "Yangi tizim",
    templates: "Tayyor shablonlar",
    templateSearch: "Shablonlarni qidirish",
    templatesTitle: "Shablonlar",
    templateCategory: "Shablon yo‘nalishi",
    templateIntro: "Yo‘nalishni tanlang va o‘zingizga mos o‘sish tizimini boshlang.",
    templateDetailIntro: "Shablonni tanlang va sozlash jarayonida moslab oling.",
    systemDescription: "Bir nechta odat va maqsadlarni bitta o‘sish tizimiga jamlang.",
    templateHint: "Sog‘liq, sport, moliya, ta’lim va boshqa yo‘nalishlardan boshlang.",
    chooseType: "Turini tanlang",
    nameIt: "Nom va niyat",
    setRhythm: "Ritmni belgilang",
    confirm: "Tasdiqlash",
    step: "Qadam",
    createdTitle: "Tizim yaratildi.",
    createdSubtitle: "Kichik boshlang. Barqaror davom eting.",
    setupSubtitle: "O‘sish tizimini sokin sozlash.",
    whatBuilding: "Nimani qurmoqchisiz?",
    whatBuildingDesc: "Bu o‘sish qatlamining shaklini tanlang. Tafsilotlarni keyin ham sozlash mumkin.",
    clearIntention: "Niyatni aniq belgilang.",
    clearIntentionDesc: "Yaxshi nom sizga kimga aylanayotganingizni eslatib turadi.",
    name: "Nomi",
    namePlaceholder: "Tizim nomi",
    why: "Bu siz uchun nega muhim?",
    whyPlaceholder: "Ixtiyoriy. Qisqa va samimiy yozing.",
    category: "Kategoriya",
    icon: "Belgi",
    accent: "Rang",
    description: "Tavsif",
    descriptionPlaceholder: "Bu tizim nimaga xizmat qiladi?",
    lightRhythm: "Yengil ritm tanlang.",
    lightRhythmDesc: "Kichik takrorlanadigan harakatlar og‘ir rejadan kuchliroq.",
    schedule: "Takrorlanish",
    weekdays: "Hafta kunlari",
    weekdaysHint: "Tanlangan kunlarda Kerak sahifasida chiqadi.",
    reminder: "Eslatma",
    starterRoutines: "Boshlang‘ich rutinlar",
    ready: "Boshlashga tayyor.",
    readyDesc: "Tizimni ko‘rib chiqing. Hozircha bu UI skeleton, backend ulanmagan.",
    type: "Turi",
    noReminder: "Eslatma yo‘q",
    routines: "Rutinlar",
    untitled: "Nomsiz tizim",
  },
  categories: {
    education: "Ta’lim",
    sport: "Sport",
    health: "Sog‘liq",
    finance: "Moliya",
    business: "Biznes",
    hobby: "Hobbi",
    mindset: "Ichki holat",
    productivity: "Samaradorlik",
    sleep: "Uyqu",
    focus: "Fokus",
    discipline: "Intizom",
    relationships: "Munosabatlar",
    personal: "Shaxsiy",
  },
  schedules: {
    daily: "Har kuni",
    monWedFri: "Du / Chor / Jum",
    tueThuSat: "Sesh / Pay / Shan",
    weekdays: "Ish kunlari",
    weekend: "Dam olish kunlari",
    custom: "Maxsus",
    weekly: "Haftalik",
    nightly: "Har kecha",
  },
  progress: {
    eyebrow: "Tahlil markazi",
    title: "Tahlil",
    subtitle: "Tahlil bo‘limlari ixcham ko‘rinishda.",
    systems: "Tizimlar",
    systemsSubtitle: "O‘sish tizimlari, rutinlar va jadval",
    aiCoach: "AI murabbiy",
    aiSubtitle: "Private Plans tahlilingiz",
    weeklyReview: "Haftalik tahlil",
    weeklySubtitle: "Haftalik ko‘rinish va refleksiya",
    growthSnapshot: "O‘sish surati",
    snapshotSubtitle: "Kunlik ball va asosiy signal",
    systemsProgress: "Tizimlar o‘sishi",
    systemsProgressSubtitle: "Maqsad va tizimlar holati",
    consistency: "Barqarorlik",
    consistencySubtitle: "Oxirgi 30 kunlik faollik xaritasi",
    missedPatterns: "Bajarilmagan naqshlar",
    missedSubtitle: "Bajarilmagan tizimlar va izohlar",
    energyInsights: "Energiya tahlili",
    energySubtitle: "Energiya o‘rtachasi va fokus signali",
    scheduleSuggestions: "Jadval tavsiyalari",
    scheduleSubtitle: "Rutin vaqtlarini yengillashtirish",
  },
  settings: {
    eyebrow: "Boshqaruv markazi",
    title: "Sozlamalar",
    subtitle: "Ixcham sozlamalar markazi.",
    profile: "Profil",
    profileSubtitle: "Hisob, tarif va holat",
    notifications: "Bildirishnomalar",
    notificationsSubtitle: "Eslatma va o‘tkazib yuborish ogohlantirishlari",
    appearance: "Ko‘rinish",
    appearanceSubtitle: "Mavzu va aksent",
    language: "Til",
    languageSubtitle: "O‘zbek, ingliz, rus",
    aiPreferences: "AI sozlamalari",
    aiSubtitle: "Murabbiy va haftalik tahlil",
    privacy: "Ma’lumot va maxfiylik",
    privacySubtitle: "Eksport, reset va maxfiylik",
    help: "Yordam markazi",
    helpSubtitle: "Qo‘llanma, savollar va yordam",
  },
};
